### ISSUE TITLE
mnist training and testing csv files

### ISSUE THREAD

**Issue by bennati** [jcsims/deebn#1]
Hi,
I want to try out your code but the csv files containing the data are not provided.
Could you upload them or at least explain how to convert the mnist dataset to the appropriate format?
Thanks!

**Comment by jcsims** [comment]
Hi! I didn't include the csv files because they are a bit large for a git repo. You can find CSV versions here: http://pjreddie.com/projects/mnist-in-csv/ with some python code for the conversion, or the originals here: http://yann.lecun.com/exdb/mnist/.
